pipeline {
    agent any
    tools {
        jdk "JDK21"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build JAR') {
            steps {
                dir('starter') {
                    sh 'mvn -B package'
                }
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -f starter/Dockerfile -t team-skeleton starter'
            }
        }
        stage('Smoke Test') {
            steps {
                sh 'docker run --rm team-skeleton'
            }
        }
    }
}
